/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activate': RouteRecordInfo<'/activate', '/activate', Record<never, never>, Record<never, never>>,
    '/activate/office': RouteRecordInfo<'/activate/office', '/activate/office', Record<never, never>, Record<never, never>>,
    '/activate/windows': RouteRecordInfo<'/activate/windows', '/activate/windows', Record<never, never>, Record<never, never>>,
    '/activate/windows-server': RouteRecordInfo<'/activate/windows-server', '/activate/windows-server', Record<never, never>, Record<never, never>>,
    '/download/': RouteRecordInfo<'/download/', '/download', Record<never, never>, Record<never, never>>,
    '/guide/': RouteRecordInfo<'/guide/', '/guide', Record<never, never>, Record<never, never>>,
    '/monitor': RouteRecordInfo<'/monitor', '/monitor', Record<never, never>, Record<never, never>>,
    '/tools': RouteRecordInfo<'/tools', '/tools', Record<never, never>, Record<never, never>>,
  }
}
