name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v6
        with:
          cache: true
          run_install: |
            - args: [--frozen-lockfile]

      - run: pnpm build
